### ISSUE TITLE
Torch 2.4.1 with CUDA 12.1 in system installed but it  fails

### ISSUE THREAD

**Issue by kyle-Liuu** [ChiSu001/SAT-HMR#3]
ERROR: Could not find a version that satisfies the requirement xformers==0.0.28.post1 (from versions: 0.0.22.post4, 0.0.22.post7, 0.0.23, 0.0.23.post1, 0.0.24, 0.0.25, 0.0.25.post1, 0.0.26, 0.0.26.post1, 0.0.27, 0.0.27.post1, 0.0.27.post2)
ERROR: No matching distribution found for xformers==0.0.28.post1

so how to install with CUDA12.1?

**Comment by ChiSu001** [comment]
Hi @kyle-Liuu , 

Thanks for your interest in our work! 

Maybe you can try to download and install the wheel [here](https://download.pytorch.org/whl/cu121/xformers-0.0.28.post1-cp311-cp311-manylinux_2_28_x86_64.whl). If the installation still fails, try the newest version(0.0.28.post3) following this [official guidance](https://github.com/facebookresearch/xformers?tab=readme-ov-file#installing-xformers) (with [PyTorch 2.5.1](https://pytorch.org/get-started/locally/)). We haven't tested this version but I think it should work.

**Comment by kyle-Liuu** [comment]
Thanks！！
Could you please upload the models and weights in this project? I have found some, but accessing Google Drive is a bit troublesome for me.

**Comment by ChiSu001** [comment]
I can send them to you via email. Please provide your email address or contact me at suchi@stu.pku.edu.cn.

**Comment by kyle-Liuu** [comment]
Please send to kyle.liuu@outlook.com
Merry Christmas
^_^

**Comment by ChiSu001** [comment]
Merry Christmas! I've sent you the files that I had previously uploaded to Google Drive. For the remaining files, you'll still need to download them directly from their official websites.

**Comment by kyle-Liuu** [comment]
I've received the files , thanks a lot.
